### ISSUE TITLE
No Deamon error

### ISSUE THREAD

**Issue by atfa** [ucetnictvi-on-line/otrs-for-docker#1]
Thanks for your great work.
But there is a error message shown on page, that said no otrs daemon running.
Thank you .

**Comment by redrick** [comment]
Hey, sry for long response time, kinda lost this one a bit, but the short answer is STEP 10 [here](http://doc.otrs.com/doc/manual/admin/6.0/en/html/manual-installation-of-otrs.html)

Longer answer would be that otrs daemon is supposed to be started manually by you from within the docker image there... so you probably know the drill so you enter container, switch to default `otrs` user:

```
su - otrs
```
you should still remain in `/opt/otrs/` folder so maybe double check, if that is true simply run:

```
bin/otrs.Daemon.pl start
```

and it should tell you that daemon started and you are done :)

Really sorry for the time it took me to respond.... also please note this is not production ready image, we use it mainly for testing as we internally use this tool heavily and also e.x. I was using it for developing ruby wrapper for otrs API and such, so for production use you may have to go through a good portion of setting in `Config.pm` and such...
